language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

sudo: false

env:
    - DB_NAME=raster_aggregation_test PYTHONPATH=$PYTHONPATH:$PWD

before_script:
  - psql -c 'create database raster_aggregation_test' -U postgres
  - psql -c 'create extension postgis' -U postgres -d raster_aggregation_test

install:
  - pip install -e .
  - pip install psycopg2==2.7.1
  - pip install flake8==3.3.0
  - pip install isort==4.2.5
  - pip install coverage==4.4.1
  - pip install coveralls

script: coverage run --include="raster-aggregation/*" ./manage.py test

after_success: coveralls

notifications:
  email: false
