dist: xenial

language: python

python:
  - '3.5'
  - '3.6'

env:
  - DB_NAME=raster_aggregation_test PYTHONPATH=$PYTHONPATH:$PWD DJANGO_SETTINGS_MODULE=tests.testproj.settings

addons:
  postgresql: 9.6
  services:
  - postgresql
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

before_script:
  - psql -U postgres -c 'create extension postgis'
  - psql -c 'create database raster_aggregation_test' -U postgres

install:
  - pip install -e .
  - pip install -U --no-deps https://github.com/geodesign/django-raster/archive/master.tar.gz
  - pip install boto3==1.5.24
  - pip install psycopg2-binary==2.7.7
  - pip install flake8==3.7.7
  - pip install isort==4.3.9
  - pip install coverage==4.5.2
  - pip install coveralls

script: coverage run --include="raster_aggregation/*" $(which django-admin.py) test

after_success: coveralls

notifications:
  email: false
